dep-install:
    - dep ensure
test:
    - go test -v -cover ./cast/... ./config/... ./errors/... ./generator/... ./log/... ./noodle/... ./requests/... ./structure/... ./util/...
scripts:
  fmt:
    - gofmt -d -l -w ./cast ./config ./errors ./log ./requests ./structure ./util
    - git status
  check:
    # TODO: didn't see any error so far ...
    # TODO: other checks, go vet, golint etc.
    - errcheck ./config ./log
  doc:
    - xdg-open http://localhost:6060/pkg/github.com/dyweb/gommon
    # NOTE: should start godoc first and then run xdg-open, but currently Ayi can't run command in parallel or background
    - godoc -http=":6060"
  docker-test:
    - docker-compose -f scripts/docker-compose.yml run --rm golang1.9
    - docker-compose -f scripts/docker-compose.yml run --rm golanglatest