language: go
sudo: false

go:
  - 1.9.x
  - 1.10.x
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure

script:
  - make install
  - go test -v -cover ./cast/... ./config/... ./generator/... ./log/... ./noodle/... ./requests/... ./runner/... ./structure/... ./util/...
  # TODO: gommon doesn't have coverage ... amazing ..