language: go
sudo: false

go:
  - "1.11"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/goimports
  - dep version
  - dep ensure

script:
  - make install
  - make test
  - make test-race
  - make vet
  - make test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)