language: go
sudo: false

go:
  - "1.11"
  - "1.12"
  - tip

env:
  - GO111MODULE=on

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - make install
  - make test
  - make test-race
  - make vet
  - make test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)