language: go
sudo: false

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure

script:
  - go test -v -cover ./...
  # TODO: gommon doesn't have coverage ... amazing ..