language: go
sudo: false

services:
  - docker

go:
  - "1.15"
  - "1.14"
  - tip

env:
  - GO111MODULE=on

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - make install-only
  - make install
  - make test
  - make test-race
  - make vet
  - make test-cover

after_script:
  - docker rm -f $(docker ps --filter="label=gommon-container" -q)

after_success:
  - bash <(curl -s https://codecov.io/bash)

